# -*- coding: utf-8 -*-
"""Federated Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tE-M1T-9BL-HglL5A7asx4b31Sdyhcdq
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data as data
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import numpy as np
import random
import os
import matplotlib.pyplot as plt
import csv
import pandas as pd
from datetime import datetime


# 定义 MLP 模型
class MLPModel(nn.Module):
    def __init__(self):
        super(MLPModel, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 200)  # 第一层，输入维度 784 -> 200
        self.fc2 = nn.Linear(200, 200)  # 第二层，200 -> 200
        self.fc3 = nn.Linear(200, 10)  # 输出层，200 -> 10
        self.relu = nn.ReLU()

    def forward(self, x):
        x = x.view(x.size(0), -1)  # 展平输入 (batch_size, 1, 28, 28) -> (batch_size, 784)
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)  # 直接输出，不使用 Softmax（因为 PyTorch 的 CrossEntropyLoss 里已经包含了）
        return x


# 加载 MNIST 数据集
def load_mnist_data(data_path="./data"):
    transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])

    if os.path.exists(os.path.join(data_path, "MNIST/raw/train-images-idx3-ubyte")):
        print("✅ MNIST 数据集已存在，跳过下载。")
    else:
        print("⬇️ 正在下载 MNIST 数据集...")

    train_data = datasets.MNIST(root=data_path, train=True, transform=transform, download=True)
    test_data = datasets.MNIST(root=data_path, train=False, transform=transform, download=True)

    # visualize_mnist_samples(train_data)
    return train_data, test_data


# 显示数据集示例图片
def visualize_mnist_samples(dataset, num_samples=10):
    fig, axes = plt.subplots(1, num_samples, figsize=(num_samples * 1.2, 1.5))
    for i in range(num_samples):
        img, label = dataset[i]
        axes[i].imshow(img.squeeze(), cmap="gray")
        axes[i].set_title(label)
        axes[i].axis("off")
    plt.show()


def split_data_by_label(dataset, num_clients=10):
    """
    手动划分数据集，每个客户端包含 10 个类别，并自定义样本数量。
    :param dataset: 原始数据集（如 MNIST）
    :param num_clients: 客户端总数
    :return: (客户端数据集, 客户端数据大小)
    """
    #手动划分的样本数量（每个客户端 10 个类别的数据量）
    # client_data_sizes = {
    #     0: {0: 600, 1: 700, 2: 600, 3: 600, 4: 500, 5: 500, 6: 100, 7: 100, 8: 100, 9: 100},
    #     1: {0: 700, 1: 600, 2: 600, 3: 600, 4: 500, 5: 100, 6: 100, 7: 100, 8: 100, 9: 600},
    #     2: {0: 500, 1: 600, 2: 700, 3: 600, 4: 100, 5: 100, 6: 100, 7: 100, 8: 600, 9: 500},
    #     3: {0: 600, 1: 600, 2: 500, 3: 100, 4: 100, 5: 100, 6: 100, 7: 500, 8: 500, 9: 700},
    #     4: {0: 600, 1: 500, 2: 100, 3: 100, 4: 100, 5: 100, 6: 600, 7: 700, 8: 500, 9: 500},
    #     5: {0: 500, 1: 100, 2: 100, 3: 100, 4: 100, 5: 600, 6: 500, 7: 600, 8: 700, 9: 600},
    #     6: {0: 100, 1: 100, 2: 100, 3: 100, 4: 700, 5: 500, 6: 600, 7: 500, 8: 500, 9: 600},
    #     7: {0: 100, 1: 100, 2: 100, 3: 600, 4: 500, 5: 600, 6: 500, 7: 600, 8: 500, 9: 100},
    #     8: {0: 100, 1: 100, 2: 500, 3: 500, 4: 600, 5: 500, 6: 600, 7: 500, 8: 100, 9: 100},
    #     9: {0: 100, 1: 700, 2: 600, 3: 600, 4: 600, 5: 500, 6: 600, 7: 100, 8: 100, 9: 100}
    # }
    client_data_sizes = {
        0: {0: 600},
        1: {1: 700},
        2: {2: 500},
        3: {3: 600},
        4: {4: 600},
        5: {5: 500},
        6: {6: 100},
        7: {7: 100},
        8: {8: 100},
        9: {9: 100}
    }



    # 统计每个类别的数据索引
    label_to_indices = {i: [] for i in range(10)}  # 记录每个类别的索引
    for idx, (_, label) in enumerate(dataset):
        label_to_indices[label].append(idx)

    # 初始化客户端数据存储
    client_data_subsets = {}
    client_actual_sizes = {i: {label: 0 for label in range(10)} for i in range(num_clients)}  # 记录实际分配的数据量

    # 遍历每个客户端，为其分配指定类别的数据
    for client_id, label_info in client_data_sizes.items():
        selected_indices = []  # 临时存储该客户端所有选中的索引
        for label, size in label_info.items():
            # 确保不超出类别数据集实际大小
            available_size = len(label_to_indices[label])
            sample_size = min(available_size, size)

            if sample_size < size:
                print(f"⚠️ 警告：类别 {label} 的数据不足，客户端 {client_id} 只能获取 {sample_size} 条样本（需求 {size} 条）")

            # 从该类别中随机抽取样本
            sampled_indices = random.sample(label_to_indices[label], sample_size)
            selected_indices.extend(sampled_indices)

            # 记录实际分配的数据量
            client_actual_sizes[client_id][label] = sample_size

        # 创建 PyTorch Subset
        client_data_subsets[client_id] = torch.utils.data.Subset(dataset, selected_indices)

    # 打印每个客户端的实际分配数据量
    print("\n📊 每个客户端实际数据分布:")
    for client_id, label_sizes in client_actual_sizes.items():
        print(f"客户端 {client_id}: {label_sizes}")

    return client_data_subsets, client_actual_sizes


# 本地训练函数
def local_train(model, train_loader, epochs=5, lr=0.01):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=lr)
    model.train()
    for epoch in range(epochs):
        for batch_x, batch_y in train_loader:
            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()
    return model.state_dict()

# 实时记录训练过程中的loss用做Fedgra
def local_train_fedgra_loss(model, train_loader, epochs=5, lr=0.01):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=lr)
    model.train()
    loss_sq_sum = 0.0

    for epoch in range(epochs):
        for batch_x, batch_y in train_loader:
            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()
            loss_sq_sum += loss.item() ** 2   

    h_i = np.sqrt(loss_sq_sum) #放大训练过程中 loss 的累积程度，从而增强客户端之间的区分度。
    return model, h_i  

#  联邦平均聚合函数
def fed_avg(global_model, client_state_dicts, client_sizes):
    global_dict = global_model.state_dict()
    subkey = [sublist[0] for sublist in client_state_dicts]
    new_client_sizes = dict(([(key, client_sizes[key]) for key in subkey]))
    total_data = sum(sum(label_sizes.values()) for label_sizes in new_client_sizes.values())  # 计算所有客户端数据总量
    for key in global_dict.keys():
        global_dict[key] = sum(
            client_state[key] * (sum(new_client_sizes[client_id].values()) / total_data)
            for (client_id, client_state) in client_state_dicts
        )
    global_model.load_state_dict(global_dict)
    return global_model


# 评估模型
def evaluate(model, test_loader):
    model.eval()
    criterion = nn.CrossEntropyLoss()
    correct, total, total_loss = 0, 0, 0.0
    with torch.no_grad():
        for batch_x, batch_y in test_loader:
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            total_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            total += batch_y.size(0)
            correct += (predicted == batch_y).sum().item()
    accuracy = correct / total * 100
    return total_loss / len(test_loader), accuracy

# # 熵权法实现
# def entropy_weight(l):
#     entropies = []
#     for X in l:
#         P = X / (np.sum(X) + 1e-12)   # 归一化得到概率分布
#         K = 1 / np.log(len(X))        
#         E = -K * np.sum(P * np.log(P + 1e-12))  #计算熵，越大越无区分度
#         entropies.append(E)            

#     # 算信息量
#     information_gain = [1 - e for e in entropies]
#     # 归一化
#     sum_ig = sum(information_gain)
#     weights = [ig / sum_ig for ig in information_gain]

#     return weights
def entropy_weight(l):
    l = np.array(l)
    
    # ✅ Step 1: Min-Max 归一化（避免负值和爆炸）
    X_norm = (l - l.min(axis=1, keepdims=True)) / (l.max(axis=1, keepdims=True) - l.min(axis=1, keepdims=True) + 1e-12)

    # ✅ Step 2: 转为概率矩阵 P_ki
    P = X_norm / (X_norm.sum(axis=1, keepdims=True) + 1e-12)

    # ✅ Step 3: 计算熵
    K = 1 / np.log(X_norm.shape[1])
    E = -K * np.sum(P * np.log(P + 1e-12), axis=1)  # shape: (2,)

    # ✅ Step 4: 计算信息效用值 & 权重
    d = 1 - E
    weights = d / np.sum(d)
    return weights.tolist()



# 灰色关联度实现
def calculate_GRC(global_model, client_models, client_losses):
    """
    计算 GRC 分数 + 熵权法权重
    修正：
      - 映射顺序错误
      - 熵权法使用错误指标
    """
    # 1. 计算参数差异（权重差异）
    # param_diffs = []
    # for model in client_models:
    #     diff = 0.0
    #     for g_param, l_param in zip(global_model.parameters(), model.parameters()):
    #         diff += torch.norm(g_param - l_param).item()
    #     param_diffs.append(diff)
    # ✅ 正确写法：使用整体参数向量计算 L2 范数（符合文献）
    param_diffs = []
    for model in client_models:
        global_vec = torch.nn.utils.parameters_to_vector(global_model.parameters()).detach()
        local_vec = torch.nn.utils.parameters_to_vector(model.parameters()).detach()
        diff = torch.norm(local_vec - global_vec).item()
        param_diffs.append(diff)

    # 2. 映射原始指标到 [0, 1] 区间（为熵权法准备）
    def map_sequence_loss(sequence):
        max_val, min_val = max(sequence), min(sequence)
        denom = max_val - min_val if abs(max_val - min_val) > 1e-8 else 1e-8
        return [(max_val - x) / denom for x in sequence]  # 越小越好，负相关

    def map_sequence_diff(sequence):
        max_val, min_val = max(sequence), min(sequence)
        denom = max_val - min_val if abs(max_val - min_val) > 1e-8 else 1e-8
        return [(x - min_val) / denom for x in sequence]  # 越大越好，正相关


    # 用于 GRC 的映射
    mapped_losses = map_sequence_loss(client_losses)
    mapped_diffs = map_sequence_diff(param_diffs)

    # 3. 熵权法计算权重（根据映射值，非 GRC）
    grc_metrics = np.vstack([mapped_losses, mapped_diffs])  # shape: (2, n_clients)
    weights = entropy_weight(grc_metrics)  # w_loss, w_diff

    # 4. 计算 GRC 分数（ξki），参考值为 1
    ref_loss, ref_diff = 1.0, 1.0
    delta_losses = [abs(x - ref_loss) for x in mapped_losses]
    delta_diffs = [abs(x - ref_diff) for x in mapped_diffs]
    all_deltas = delta_losses + delta_diffs
    max_delta, min_delta = max(all_deltas), min(all_deltas)

    grc_losses = []
    grc_diffs = []
    rho = 0.5  # 区分度因子
    for d_loss, d_diff in zip(delta_losses, delta_diffs):
        grc_loss = (min_delta + rho * max_delta) / (d_loss + rho * max_delta)
        grc_diff = (min_delta + rho * max_delta) / (d_diff + rho * max_delta)
        grc_losses.append(grc_loss)
        grc_diffs.append(grc_diff)

    # 5. 加权求和得到最终 GRC 分数
    grc_losses = np.array(grc_losses)
    grc_diffs = np.array(grc_diffs)
    weighted_score = grc_losses * weights[0] + grc_diffs * weights[1]

    # 调试（每个客户端的 loss、diff、得分）
    print("\n GRC得分]")
    for i in range(len(client_models)):
        print(f"Client {i} | loss: {client_losses[i]:.4f}, diff: {param_diffs[i]:.4f}, "
              f"mapped_loss: {mapped_losses[i]:.4f}, mapped_diff: {mapped_diffs[i]:.4f}, "
              f"GRC: {weighted_score[i]:.4f}")
    print(f"熵权法权重: w_loss = {weights[0]:.4f}, w_diff = {weights[1]:.4f}")

    return weighted_score, weights


# 客户端选择器，4.15更新，加入 fairness_tracker
def select_clients(client_loaders, use_all_clients=False, num_select=None,
                   select_by_loss=False, global_model=None, grc=False,
                   fairness_tracker=None):  

    if grc:  # 使用 GRC 选择客户端
        client_models = []
        # 1. 训练本地模型并计算损失
        client_losses = []
        for client_id, client_loader in client_loaders.items():
            local_model = MLPModel()
            local_model.load_state_dict(global_model.state_dict())  # 同步全局模型
            trained_model, h_i = local_train_fedgra_loss(local_model, client_loader, epochs=5, lr=0.01)
            client_models.append(trained_model)
            client_losses.append(h_i)

        # 2. 计算 GRC 分数
        grc_scores, grc_weights = calculate_GRC(global_model, client_models, client_losses)
        select_clients.latest_weights = grc_weights  # 记录权重

        # 3. 按 GRC 分数排序（从高到低，GRC越高表示越好）
        client_grc_pairs = list(zip(client_loaders.keys(), grc_scores))
        client_grc_pairs.sort(key=lambda x: x[1], reverse=True)  # 降序排序

        # 4. 选择 GRC 最高的前 num_select 个客户端
        selected_clients = [client_id for client_id, _ in client_grc_pairs[:num_select]]
        
        # 更新公平性机制：防止长期未被选中
        # fairness_threshold = 10  # 允许最大未参与轮数
        # force_selected = []

        # for client_id in client_loaders.keys():
        #     if client_id in selected_clients:
        #         fairness_tracker[client_id] = 0  # 被选中，重置 F_i
        #     else:
        #         fairness_tracker[client_id] += 1
        #         if fairness_tracker[client_id] >= fairness_threshold:
        #             force_selected.append(client_id)
        #             fairness_tracker[client_id] = 0
        #             print(f" Fairness 强制选入客户端: {client_id}")

        # selected_clients += force_selected  # 合并最终要选的客户端

        # return selected_clients  

        # =========  GRC + Fairness 限制数量版本 =========
        fairness_threshold = 10
        all_clients = list(client_loaders.keys())

        # Step 1: 所有客户端未被选中 → Fi += 1
        for client_id in all_clients:
            fairness_tracker[client_id] += 1

        # Step 2: 找出 Fi 最大的客户端（并且 Fi ≥ 阈值）
        fairness_candidates = [
            (cid, fairness_tracker[cid]) for cid in all_clients if fairness_tracker[cid] >= fairness_threshold
        ]
        fairness_candidates.sort(key=lambda x: x[1], reverse=True)

        selected_clients = []
        used_set = set()

        # Step 3a: 先选 Fi 最大的最多 num_select 个
        for cid, _ in fairness_candidates:
            if len(selected_clients) >= num_select:
                break
            selected_clients.append(cid)
            used_set.add(cid)

        if selected_clients:
            print(f"🔁 Fairness 触发，优先选入: {selected_clients}")

        # Step 3b: 不够就补 GRC 高分
        for cid, _ in client_grc_pairs:
            if len(selected_clients) >= num_select:
                break
            if cid not in used_set:
                selected_clients.append(cid)
                used_set.add(cid)

        # Step 4: 重置被选中的客户端 Fi
        for cid in selected_clients:
            fairness_tracker[cid] = 0

        return selected_clients


    # 其余选择逻辑保持不变

    if use_all_clients is True:
        print("Selecting all clients")
        return list(client_loaders.keys())

    if num_select is None:
        raise ValueError("If use_all_clients=False, num_select cannot be None!")

    if select_by_loss and global_model:
        client_losses = {}
        
        for client_id, loader in client_loaders.items():
            local_model = MLPModel()
            local_model.load_state_dict(global_model.state_dict())
            local_train(local_model, loader, epochs=5, lr=0.01) 
            loss, _ = evaluate(local_model, loader)  
            client_losses[client_id] = loss
        selected_clients = sorted(client_losses, key=client_losses.get, reverse=True)[:num_select]
        print(f"Selected {num_select} clients with the highest loss: {selected_clients}")
    else:
        selected_clients = random.sample(list(client_loaders.keys()), num_select)
        print(f"Randomly selected {num_select} clients: {selected_clients}")

    return selected_clients


def update_communication_counts(communication_counts, selected_clients, event):
    """
    客户端通信计数
    - event='receive' 表示客户端接收到全局模型
    - event='send' 表示客户端上传本地模型
    - event='full_round' 仅在客户端完成完整收发时增加
    """
    for client_id in selected_clients:
        communication_counts[client_id][event] += 1

        # 仅当客户端完成一次完整的 send 和 receive 时增加 full_round
        if event == "send" and communication_counts[client_id]['receive'] > 0:
            communication_counts[client_id]['full_round'] += 1


def main():
    torch.manual_seed(0)
    random.seed(0)
    np.random.seed(0)

    # 加载 MNIST 数据集
    train_data, test_data = load_mnist_data()

    # 生成客户端数据集，每个客户端包含多个类别
    client_datasets, client_data_sizes = split_data_by_label(train_data)

    # 创建数据加载器
    client_loaders = {client_id: data.DataLoader(dataset, batch_size=32, shuffle=True)
                      for client_id, dataset in client_datasets.items()}
    test_loader = data.DataLoader(test_data, batch_size=32, shuffle=False)

    # 初始化全局模型
    global_model = MLPModel()
    global_accuracies = []  # 记录每轮全局模型的测试集准确率
    total_communication_counts = []  # 记录每轮客户端通信次数
    rounds = 100  # 联邦学习轮数
    use_all_clients = False  # 是否进行客户端选择
    num_selected_clients = 2  # 每轮选择客户端训练数量
    use_loss_based_selection = False  # 是否根据 loss 选择客户端
    grc = True

    # 初始化通信计数器
    communication_counts = {}
    fairness_tracker = {}  # Fairness tracker 初始化

    for client_id in client_loaders.keys():
        communication_counts[client_id] = {
            'send': 0,
            'receive': 0,
            'full_round': 0
        }
        fairness_tracker[client_id] = 0  # 初始为 0

    # 实验数据存储 CSV
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    csv_filename = f"training_data_{timestamp}.csv"
    csv_data = []

    for r in range(rounds):
        print(f"\n🔄 第 {r + 1} 轮聚合")
        # 选择客户端
        
        selected_clients = select_clients(
            client_loaders,
            use_all_clients=use_all_clients,
            num_select=num_selected_clients,
            select_by_loss=use_loss_based_selection,
            global_model=global_model,
            grc=grc,
            fairness_tracker=fairness_tracker                            
        )
        # # 设置随机阻断某个客户端的接收记录（验证用）
        # blocked_client = random.choice(selected_clients)
        # print(f" Blocking client {blocked_client} from receiving, skipping the receive event record.")

        # for client_id in selected_clients:
        #     if client_id == blocked_client:
        #         continue  # 直接跳过 receive 记录
        #     update_communication_counts(communication_counts, [client_id], "receive")

        # 记录客户端接收通信次数
        update_communication_counts(communication_counts, selected_clients, "receive")
        client_state_dicts = []

        # 客户端本地训练
        for client_id in selected_clients:
            client_loader = client_loaders[client_id]
            local_model = MLPModel()
            local_model.load_state_dict(global_model.state_dict())  # 复制全局模型参数
            local_state = local_train(local_model, client_loader, epochs=5, lr=0.01)  # 训练 1 轮
            client_state_dicts.append((client_id, local_state))  # 存储 (客户端ID, 训练后的参数)

            update_communication_counts(communication_counts, [client_id], "send")  # 记录客户端上报通信次数

            param_mean = {name: param.mean().item() for name, param in local_model.named_parameters()}
            print(f"  ✅ 客户端 {client_id} 训练完成 | 样本数量: {sum(client_data_sizes[client_id].values())}")
            print(f"  📌 客户端 {client_id} 模型参数均值: {param_mean}")

        # 计算本轮通信次数
        total_send = sum(communication_counts[c]['send'] - (communication_counts[c]['full_round'] - 1) for c in selected_clients)
        total_receive = sum(communication_counts[c]['receive'] - (communication_counts[c]['full_round'] - 1) for c in selected_clients)
        total_comm = total_send + total_receive  # 每轮独立的总通信次数

        # 如果不是第一轮，累加前一轮的通信次数
        if len(total_communication_counts) > 0:
            total_comm += total_communication_counts[-1]
        total_communication_counts.append(total_comm)

        # 聚合模型参数
        global_model = fed_avg(global_model, client_state_dicts, client_data_sizes)

        # # 计算全局模型参数平均值
        # global_param_mean = {name: param.mean().item() for name, param in global_model.named_parameters()}
        # print(f"🔄 轮 {r + 1} 结束后，全局模型参数均值: {global_param_mean}")

        # 评估模型
        loss, accuracy = evaluate(global_model, test_loader)
        global_accuracies.append(accuracy)
        print(f"📊 测试集损失: {loss:.4f} | 测试集准确率: {accuracy:.2f}%")

        # 记录数据到 CSV
        if grc and hasattr(select_clients, 'latest_weights'):
            w_loss = select_clients.latest_weights[0]
            w_diff = select_clients.latest_weights[1]
            print(f"📈 Round {r+1} | GRC 权重: w_loss = {w_loss:.4f}, w_diff = {w_diff:.4f}")

        else:
            w_loss = 'NA'
            w_diff = 'NA'

        csv_data.append([
            r + 1,
            accuracy,
            total_comm,
            ",".join(map(str, selected_clients)),
            w_loss,
            w_diff
        ])
        df = pd.DataFrame(csv_data, columns=[
            'Round', 'Accuracy', 'Total communication counts', 'Selected Clients',
            'GRC Weight - Loss', 'GRC Weight - Diff'])
        df.to_csv(csv_filename, index=False)

    # 输出最终模型的性能
    final_loss, final_accuracy = evaluate(global_model, test_loader)
    print(f"\n🎯 Loss of final model test dataset: {final_loss:.4f}")
    print(f"🎯 Final model test set accuracy: {final_accuracy:.2f}%")

    # 输出通信记录
    print("\n Client Communication Statistics:")
    for client_id, counts in communication_counts.items():
        print(
            f"Client {client_id}: Sent {counts['send']} times, Received {counts['receive']} times, Completed full_round {counts['full_round']} times")

    # 可视化全局模型准确率 vs 轮次
    plt.figure(figsize=(8, 5))
    plt.plot(range(1, rounds + 1), global_accuracies, marker='o', linestyle='-', color='b', label="Test Accuracy")
    plt.xlabel("Federated Learning Rounds")
    plt.ylabel("Accuracy")
    plt.title("Test Accuracy Over Federated Learning Rounds")
    plt.legend()
    plt.grid(True)
    plt.show()

    # 可视化全局模型准确率 vs 客户端完整通信次数
    plt.figure(figsize=(8, 5))
    plt.plot(total_communication_counts, global_accuracies, marker='s', linestyle='-', color='r',
             label="Test Accuracy vs. Communication")
    plt.xlabel("Total Communication Count per Round")
    plt.ylabel("Accuracy")
    plt.title("Test Accuracy vs. Total Communication")
    plt.legend()
    plt.grid(True)
    plt.show()




# 高 Loss 跨轮次选择

def main2():
    torch.manual_seed(0)
    random.seed(0)
    np.random.seed(0)

    train_data, test_data = load_mnist_data()
    client_datasets, client_data_sizes = split_data_by_label(train_data)
    client_loaders = {client_id: data.DataLoader(dataset, batch_size=32, shuffle=True)
                      for client_id, dataset in client_datasets.items()}
    test_loader = data.DataLoader(test_data, batch_size=32, shuffle=False)

    global_model = MLPModel()
    global_accuracies = []
    total_communication_counts = []
    rounds = 100
    num_selected_clients = 2

    communication_counts = {cid: {'send': 0, 'receive': 0, 'full_round': 0} for cid in client_loaders.keys()}
    client_loss_history = {cid: [] for cid in client_loaders.keys()}
    local_model_cache = {}  # ⬅️ 本地缓存用于跨轮次复用模型
    selected_clients = []   # ⬅️ 每轮更新，用于非通信轮复用

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    csv_filename = f"training_data_{timestamp}_main2.csv"
    csv_data = []

    for r in range(rounds):
        print(f"\n🔄 第 {r + 1} 轮聚合")

        is_comm_round = False

        if r % 3 == 0:
            current_losses = {}
            for cid, loader in client_loaders.items():
                loss, _ = evaluate(global_model, loader)
                current_losses[cid] = loss
                client_loss_history[cid].append(loss)

            weighted_losses = {}
            for cid in client_loaders.keys():
                history = client_loss_history[cid][-3:]
                if len(history) == 3:
                    weights = [0.5, 0.25, 0.25]
                elif len(history) == 2:
                    weights = [0.6, 0.4]
                else:
                    weights = [1.0]
                weighted_losses[cid] = sum(h * w for h, w in zip(history, weights)) / sum(weights)

            selected_clients = sorted(weighted_losses, key=weighted_losses.get, reverse=True)[:num_selected_clients]
            print(f"📌 通信轮 | Selected clients with highest weighted loss: {selected_clients}")

            # ⬇️ 通信轮才做模型训练与更新通信记录
            update_communication_counts(communication_counts, selected_clients, "receive")
            client_state_dicts = []

            for cid in selected_clients:
                loader = client_loaders[cid]
                local_model = MLPModel()
                local_model.load_state_dict(global_model.state_dict())
                local_state = local_train(local_model, loader, epochs=1, lr=0.01)
                local_model_cache[cid] = local_model  # ⬅️ 缓存模型
                client_state_dicts.append((cid, local_state))
                update_communication_counts(communication_counts, [cid], "send")

            is_comm_round = True

        else:
            print(f"⏳ 非通信轮 | 使用上一轮缓存模型: {selected_clients}")
            client_state_dicts = []
            for cid in selected_clients:
                if cid in local_model_cache:
                    client_state_dicts.append((cid, local_model_cache[cid].state_dict()))
                else:
                    print(f"⚠️ 缓存缺失客户端 {cid}，跳过")

        # 通信统计
        if is_comm_round:
            total_send = sum(communication_counts[c]['send'] - (communication_counts[c]['full_round'] - 1) for c in selected_clients)
            total_receive = sum(communication_counts[c]['receive'] - (communication_counts[c]['full_round'] - 1) for c in selected_clients)
            total_comm = total_send + total_receive
        else:
            total_comm = 0

        if total_communication_counts:
            total_comm += total_communication_counts[-1]
        total_communication_counts.append(total_comm)

        # 聚合
        global_model = fed_avg(global_model, client_state_dicts, client_data_sizes)
        loss, acc = evaluate(global_model, test_loader)
        global_accuracies.append(acc)
        print(f"📊 测试集损失: {loss:.4f} | 测试集准确率: {acc:.2f}%")

        csv_data.append([r + 1, acc, total_comm, ",".join(map(str, selected_clients)), 'NA', 'NA'])
        df = pd.DataFrame(csv_data, columns=['Round', 'Accuracy', 'Total communication counts', 'Selected Clients', 'GRC Weight - Loss', 'GRC Weight - Diff'])
        df.to_csv(csv_filename, index=False)

    final_loss, final_acc = evaluate(global_model, test_loader)
    print(f"\n🎯 Final Loss: {final_loss:.4f}")
    print(f"🎯 Final Accuracy: {final_acc:.2f}%")




# Fedgra跨轮次选择

def main3():
    torch.manual_seed(0)
    random.seed(0)
    np.random.seed(0)

    train_data, test_data = load_mnist_data()
    client_datasets, client_data_sizes = split_data_by_label(train_data)
    client_loaders = {cid: data.DataLoader(dataset, batch_size=32, shuffle=True) for cid, dataset in client_datasets.items()}
    test_loader = data.DataLoader(test_data, batch_size=32, shuffle=False)

    global_model = MLPModel()
    global_accuracies = []
    total_communication_counts = []
    rounds = 100
    num_selected_clients = 2

    communication_counts = {cid: {'send': 0, 'receive': 0, 'full_round': 0} for cid in client_loaders}
    client_grc_history = {cid: [] for cid in client_loaders}
    local_model_cache = {}
    selected_clients = []

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    csv_filename = f"training_data_{timestamp}_main3.csv"
    csv_data = []

    total_comm = 0  # ✅ 用于累计通信总数

    for r in range(rounds):
        print(f"\n🔄 第 {r + 1} 轮聚合")
        w_loss, w_diff = 'NA', 'NA'
        round_comm = 0
        is_comm_round = False

        if r % 3 == 0:
            client_models, client_losses = [], []
            for cid, loader in client_loaders.items():
                model = MLPModel()
                model.load_state_dict(global_model.state_dict())
                local_train(model, loader, epochs=1, lr=0.01)
                client_models.append(model)
                loss, _ = evaluate(model, loader)
                client_losses.append(loss)

            grc_scores, grc_weights = calculate_GRC(global_model, client_models, client_losses)
            w_loss, w_diff = grc_weights
            print(f"📈 Round {r+1} | GRC 权重: w_loss = {w_loss:.4f}, w_diff = {w_diff:.4f}")

            for idx, cid in enumerate(client_loaders.keys()):
                client_grc_history[cid].append(grc_scores[idx])

            weighted_grc = {}
            for cid in client_loaders:
                history = client_grc_history[cid][-3:]
                if len(history) == 3:
                    weights = [0.5, 0.25, 0.25]
                elif len(history) == 2:
                    weights = [0.6, 0.4]
                else:
                    weights = [1.0]
                weighted_grc[cid] = sum(h * w for h, w in zip(history, weights)) / sum(weights)

            selected_clients = sorted(weighted_grc, key=weighted_grc.get, reverse=True)[:num_selected_clients]
            print(f"📌 通信轮 | Selected clients: {selected_clients}")
            update_communication_counts(communication_counts, selected_clients, "receive")
            is_comm_round = True

        else:
            print(f"⏳ 非通信轮 | 复用客户端模型: {selected_clients}")

        client_state_dicts = []

        for cid in selected_clients:
            if is_comm_round:
                loader = client_loaders[cid]
                model = MLPModel()
                model.load_state_dict(global_model.state_dict())
                local_train(model, loader, epochs=1, lr=0.01)
                local_model_cache[cid] = model
                client_state_dicts.append((cid, model.state_dict()))
                update_communication_counts(communication_counts, [cid], "send")
                round_comm += 2  # ✅ 1 send + 1 receive
            else:
                if cid in local_model_cache:
                    client_state_dicts.append((cid, local_model_cache[cid].state_dict()))
                else:
                    print(f"⚠️ 客户端 {cid} 无模型缓存，跳过")

        # ✅ 跨轮次通信总数累计
        total_comm += round_comm
        total_communication_counts.append(total_comm)

        global_model = fed_avg(global_model, client_state_dicts, client_data_sizes)
        loss, acc = evaluate(global_model, test_loader)
        global_accuracies.append(acc)
        print(f"📊 测试集损失: {loss:.4f} | 测试集准确率: {acc:.2f}%")

        csv_data.append([r + 1, acc, total_comm, ",".join(map(str, selected_clients)), w_loss, w_diff])
        df = pd.DataFrame(csv_data, columns=[
            'Round', 'Accuracy', 'Total communication counts',
            'Selected Clients', 'GRC Weight - Loss', 'GRC Weight - Diff'
        ])
        df.to_csv(csv_filename, index=False)

    final_loss, final_acc = evaluate(global_model, test_loader)
    print(f"\n🎯 Final Loss: {final_loss:.4f}")
    print(f"🎯 Final Accuracy: {final_acc:.2f}%")





if __name__ == "__main__":
    main()
